Task/05-calendar
js-tasks-ru/htmlcss-20220120_chexov34 pull request #10
Opened 2022-02-05 12:42 UTC by chex0v

Added calendar widget

2022-02-05 12:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 20:04 UTC, GSemikozov requested changes

2022-02-07 20:04 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.c-calendar--item_day {
класс немного неправильно написан)
.c-calendar--item_day -> .c-calendar__item--day наверно так?

2022-02-08 12:43 UTC, GSemikozov approved these changes

2022-02-08 12:43 UTC, merged