feature 03-lection-buttons
js-tasks-ru/htmlcss-20220120_chexov34 pull request #3
Opened 2022-01-25 22:24 UTC by chex0v

Added css styles for three new buttons(primary, secondary, alternate)  with :disabled and :hover types
Added examples for new buttons

2022-01-25 22:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-26 08:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-26 12:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-26 23:18 UTC, GSemikozov requested changes

2022-01-26 23:18 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <main class="l-container l-container--main">
а где стили контейнера?)

2022-01-26 23:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: all 0.4s linear;
0.4 все-таки многовато, желательно укладываться в промежуток 200-300ms, но это не критично, коммент можно скипнуть

2022-01-27 09:36 UTC, chex0v commented on 03-lection1/01-button/index.html
> +        <main class="l-container l-container--main">
> а где стили контейнера?)
Ну я думал мы эту тему не прошли, поэтому не стал добавлять
Добавил, надеюсь верное направление)

2022-01-27 09:37 UTC, chex0v commented on 03-lection1/01-button/button.css
> +    transition: all 0.4s linear;
> 0.4 все-таки многовато, желательно укладываться в промежуток 200-300ms, но это не критично, коммент можно скипнуть


Поменял на 0.3

2022-01-27 21:49 UTC, GSemikozov approved these changes

2022-01-27 21:49 UTC, merged