Task/03 lection accordion
js-tasks-ru/htmlcss-20220120_chexov34 pull request #4
Opened 2022-01-26 19:52 UTC by chex0v

Added accordion with example

2022-01-26 19:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-26 23:20 UTC, GSemikozov requested changes

2022-01-26 23:20 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="c-accordion mb-md" open>
поскольку аккордион - это цельный компонент, то я бы предложил все секции сделать единым целым, переименовав c-accordion в c-accordion__item, а все items обернул бы в div с классом c-accordion

2022-01-27 09:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 10:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-27 10:38 UTC, chex0v commented on 03-lection1/02-accordion/index.html
> +        <details class="c-accordion mb-md" open>
> поскольку аккордион - это цельный компонент, то я бы предложил все секции сделать единым целым, переименовав c-accordion в c-accordion__item, а все items обернул бы в div с классом c-accordion

Поменял

2022-01-28 12:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-28 19:11 UTC, GSemikozov approved these changes

2022-01-28 19:11 UTC, merged